version: "3.4"

services:
  backend:
    build: ./backend
    container_name: backend
    deploy:
      resources:
        limits:
          memory: 200m
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    deploy:
      resources:
        limits:
          memory: 200m
    env_file:
      - ./frontend/.env
    ports:
      - "3000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
